name: Scheduled Scraper

on:
  schedule:
    - cron: '0 */6 * * *' # Jalan setiap 6 jam
  workflow_dispatch: # Bisa dijalankan manual klik tombol

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-node-version: '18'
      - run: npm install
      - name: Run Scraper
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/scraper.js
